# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=128)),
                ('b_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('u_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='b_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationAndPermission.User'),
        ),
    ]
