# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=32)),
                ('a_weight', models.FloatField(default=10)),
            ],
        ),
    ]
