# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerLearn', '0002_spider'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32)),
                ('p_age', models.IntegerField(default=18)),
            ],
        ),
    ]
